endpoint: "play.min.io"
secure: true
accessKey: "MINIO_ACCESS_KEY"
secretKey: "MINIO_SECRET_KEY"
bucket: "schematics"
# Default schematic file extension. Allowed: "schem" (recommended) or "schematic".
extension: "schem"

# Where to place downloaded schematic files on disk
downloadDir: "plugins/SchemFlow/schematics"

# Storage hierarchy (S3 object keys)
storage:
  rootDir: "FlowStack/SchemFlow"   # Root folder prefix in the bucket
  defaultGroup: "default"         # Default group if none provided

# Startup behavior
autoListOnStart: true
# Optional: name of schematic to fetch on start (leave blank to skip)
fetchOnStart: ""

# Schematic cache auto-refresh interval (seconds). Set 0 to disable periodic refresh.
cacheRefreshSeconds: 60

# Provisioning (WDB replacement)
provisionOnStartup: false
worlds:
  - name: "example_world"
    enabled: false
    flat: true
    generatorSettings: '{"biome": "minecraft:plains","layers": []}'
    schem: "example_world"    # schematic name (without extension)
    pasteAt: "0,64,0"
    gamerules:
      doMobSpawning: false
      doDaylightCycle: false
      doWeatherCycle: false
      announceAdvancements: false
      disableRaids: true
      doFireTick: false
      doPatrolSpawning: false
      doTraderSpawning: false
      doVinesSpread: false
      doWardenSpawning: false
      globalSoundEvents: false
      mobGriefing: false
      randomTickSpeed: 0
      snowAccumulationHeight: 0
      spawnChunkRadius: 0