name: SchemFlow
main: com.c4g7.schemflow.SchemFlowPlugin
version: "${project.version}"
api-version: '1.21'
author: c4g7
website: https://bio.c4g7.com
softdepend:
  - Skript
  - WorldEdit
  - FastAsyncWorldEdit
commands:
  'SchemFlow':
    description: SchemFlow primary command
    usage: "/SchemFlow <help|list|fetch [group:]name|pos1|pos2|upload id [-flags] [-group name]|paste [group:]name [-flags]|delete [group:]name|restore name [-group dest]|trash [clear --confirm]|undo|redo|cache|reload|provision world|groups|group create name|group delete name|group rename old new>"
    aliases: [schem]
permissions:
  schemflow.admin:
    default: op
    description: Full access to all SchemFlow commands
  schemflow.help:
    default: true
    description: View help for SchemFlow commands
  schemflow.reload:
    default: op
    description: Reload config and services
  schemflow.cache:
    default: op
    description: Refresh schematic cache
  schemflow.list:
    default: true
    description: List available schematics
  schemflow.fetch:
    default: true
    description: Download schematic
  schemflow.pos1:
    default: true
    description: Set first selection position
  schemflow.pos2:
    default: true
    description: Set second selection position
  schemflow.upload:
    default: op
    description: Export and upload schematic
  schemflow.paste:
    default: op
    description: Paste schematic at location
  schemflow.delete:
    default: op
    description: Delete schematic from storage
  schemflow.restore:
    default: op
    description: Restore schematic from trash
  schemflow.trash.clear:
    default: op
    description: Permanently clear all trashed schematics (requires --confirm)
  schemflow.provision:
    default: op
    description: Provision world base
  schemflow.groups:
    default: op
    description: List groups
  schemflow.group.create:
    default: op
    description: Create a new group
  schemflow.group.delete:
    default: op
    description: Delete a group and all its schematics (non-default only)
  schemflow.group.rename:
    default: op
    description: Rename a group (non-default only)