name: Build and Release

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Determine version
      id: version
      shell: bash
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          VER="${GITHUB_REF#refs/tags/v}"
          MVN_REV="-Drevision=$VER"
        else
          VER="0.5"
          MVN_REV=""
        fi
        echo "ver=$VER" >> "$GITHUB_OUTPUT"
        echo "mvn_rev=$MVN_REV" >> "$GITHUB_OUTPUT"

    - name: Build with Maven
      run: mvn ${{ steps.version.outputs.mvn_rev }} clean compile test-compile package --batch-mode
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SchemFlow-${{ steps.version.outputs.ver }}
        path: target/SchemFlow-*.jar
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Extract tag version
      id: tag
      shell: bash
      run: echo "ver=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

    - name: Build release JAR
      run: mvn -Drevision=${{ steps.tag.outputs.ver }} clean package --batch-mode
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/SchemFlow-*.jar
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}